name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test

    - name: Crear imagen de Docker
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: miguel7ctac/devops:latest
        dockerfile: Dockerfile
        build-args: |
          ARG_NOMBRE=valor

