name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Instalar dependencias
      run: |
        npm install

    - name: Ejecutar pruebas
      run: |
        npm test

    - name: Crear imagen de Docker
      if: success()
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
